"""Plain-language explanation generator.

Converts a `Decision` (plus the qname it was made about) into a structured
list of `Reason`s and a templated human-readable string. Per the
architecture: the human string is templated from structured reasons, not
generated by an LLM at query time. Latency-safe, deterministic, no
external dependency.

The same `explain()` function will be reused by:
- The forwarder's BLOCK log line (this PR)
- The future `sentinel-dns explain <domain>` CLI command
"""

from __future__ import annotations

from dataclasses import dataclass

from sentinel_dns.cache import Decision
from sentinel_dns.classifier import heuristic_signals


@dataclass(frozen=True)
class Reason:
    """A single structured signal contributing to a decision.

    `signal` is a short stable code (suitable for log fields and metrics);
    `human` is the user-facing string for that signal in isolation.
    """

    signal: str
    human: str


@dataclass(frozen=True)
class Explanation:
    """Plain-language + structured explanation of a decision."""

    qname: str
    decision: str  # "block" or "allow"
    reasons: list[Reason]
    human: str

    @property
    def signal_codes(self) -> list[str]:
        return [r.signal for r in self.reasons]


def explain(qname: str, decision: Decision) -> Explanation:
    """Generate a structured + human-readable explanation.

    Re-runs `heuristic_signals` cheaply (~7µs per spike-A microbench) to
    recover the structured reasons that drove `heuristic_score`. We don't
    persist the structured reasons in the cache because they're tiny to
    recompute and storing them would bloat the cache.
    """
    reasons: list[Reason] = []

    # Block source comes first — it's the load-bearing reason.
    if decision.block_source == "blocklist":
        reasons.append(
            Reason(
                signal="blocklist",
                human="Listed on a known-malware threat feed (URLhaus).",
            )
        )
    elif decision.block_source == "classifier":
        confidence = round(decision.ml_score * 100)
        reasons.append(
            Reason(
                signal="lexical_classifier",
                human=f"Our ML model is {confidence}% confident this name looks malicious.",
            )
        )

    # Heuristic signals — included regardless of block source. They add
    # color even on a blocklist hit, and they're often the only signals
    # available when the classifier didn't run (blocklist-only mode).
    sigs = heuristic_signals(qname)
    if sigs.abused_tld:
        tld = qname.rsplit(".", 1)[-1]
        reasons.append(
            Reason(
                signal="abused_tld",
                human=f"Uses the .{tld} TLD, frequently abused for short-lived attack domains.",
            )
        )
    if sigs.very_high_entropy:
        reasons.append(
            Reason(
                signal="very_high_entropy",
                human="The name has very high character entropy, strongly suggesting it's algorithmically generated.",
            )
        )
    elif sigs.high_entropy:
        reasons.append(
            Reason(
                signal="high_entropy",
                human="The name has high character entropy, suggesting it may be algorithmically generated.",
            )
        )
    if sigs.very_long:
        reasons.append(
            Reason(
                signal="very_long",
                human=f"Unusually long domain name ({len(qname)} characters).",
            )
        )
    elif sigs.long:
        reasons.append(
            Reason(
                signal="long",
                human=f"Long domain name ({len(qname)} characters).",
            )
        )
    if sigs.digit_heavy:
        reasons.append(
            Reason(
                signal="digit_heavy",
                human="Unusually digit-heavy for a typical domain name.",
            )
        )
    if sigs.many_dashes:
        reasons.append(
            Reason(
                signal="many_dashes",
                human="Contains many dashes — common in typosquats and DGA-generated names.",
            )
        )
    if sigs.hex_label:
        reasons.append(
            Reason(
                signal="hex_label",
                human="Contains a long hex string, common in algorithmically-generated domains.",
            )
        )
    if sigs.consonant_run:
        reasons.append(
            Reason(
                signal="consonant_run",
                human="Contains an unusual run of consonants, suggesting non-natural-language origin.",
            )
        )

    decision_str = "block" if decision.would_block else "allow"
    human = _stitch(qname, decision_str, reasons)
    return Explanation(qname=qname, decision=decision_str, reasons=reasons, human=human)


def _stitch(qname: str, decision: str, reasons: list[Reason]) -> str:
    """Combine reason strings into one paragraph.

    Trivial concatenation today. A cleaner version that lowercases joined
    fragments and uses commas + 'and' is post-v0.1 polish.
    """
    if not reasons:
        if decision == "block":
            return f"{qname} was blocked but no specific signals were recorded — check logs."
        return f"{qname} did not match any blocking signals."
    return " ".join(r.human for r in reasons)
